version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run: $PWD/scripts/checkout.sh /tmp/workspace $PWD/standaardenregister.json
      - run: if [ -e /tmp/workspace/checkouts.txt ] ; then cat /tmp/workspace/checkouts.txt ; fi
      - run: if [ -e /tmp/workspace/rawcheckouts.txt ] ; then cat /tmp/workspace/rawcheckouts.txt ; fi
      - run: if [ -e /home/circleci/project/changes.txt ] ; then cat /home/circleci/project/changes.txt ; fi
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - checkouts.txt
            - rawcheckouts.txt
            - changedstandards.json
            - haschangedpublications.json
            - links.txt
            - src/
            - raw-input/
workflows:
  version: 2
  create_detail_page:
    jobs:
      - checkout
      - render-html:
          requires:
            - checkout

