version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run: chmod -R 777 $PWD/scripts
      - run: $PWD/scripts/checkout.sh /tmp/workspace $PWD/standaardenregister.json
      - run: if [ -e /tmp/workspace/checkouts.txt ] ; then cat /tmp/workspace/checkouts.txt ; fi
      - run: if [ -e /tmp/workspace/rawcheckouts.txt ] ; then cat /tmp/workspace/rawcheckouts.txt ; fi
      - run: if [ -e /home/circleci/project/changes.txt ] ; then cat /home/circleci/project/changes.txt ; fi
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - changedstandards.json
            - repositories/
  render-html:
    docker:
      - image: ddvlanck/html-page-generator:1.0.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: chmod -R 777 $PWD/scripts
      - run:
          name: Creating HTML pages for modified or new standards
          command: $PWD/scripts/generator.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
          - html_pages/
  push-to-repository:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "c1:60:33:1c:43:ce:00:5b:66:61:79:8b:67:d4:0c:28"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            rm -rf OSLO-Generated
            git clone https://github.com/ddvlanck/OSLO-StandaardenGenerated
      - run:
          name: Clean the generated directory
          workdir: /tmp/OSLO-StandaardenGenerated
          command: |
            git fetch origin
#            if [ "`cat /tmp/workspace/haschangedpublications.json`" == "false" ] ; then git rm -r --force * ; fi
      - run:
          name: Copy generated assets
          workdir: /tmp/workspace
          command: |
            mkdir -p /tmp/OSLO-Generated/result
            if [ -d html_pages ] ; then if [ ! "$(ls -A html_pages)" ] ; then echo "directory html_pages is empty" ; else cp -R html_pages/* /tmp/OSLO-StandaardenGenerated/result ; fi fi
      #- run:
      #    name: insert the commit
      #    command: |
      #      export TAG=`echo "${CIRCLE_SHA1}" | cut -c1-15`
      #      echo "{\"commit\" : \"$TAG\"}" > /tmp/OSLO-Generated/report/commit.json
      - run:
          name: Push results to Github repository OSLO-Generated
          workdir: /tmp/OSLO-Generated
          command: |
            git config user.email "oslo@kb.vlaanderen.be"
            git config user.name "Circle CI Builder"
            git add .
            git status
            git commit -m "Applying changes from newest commit " --allow-empty
            export TAG=`echo "${CIRCLE_SHA1}" | cut -c1-15`
            git tag "${TAG}"
            git push --force "${CIRCLE_BRANCH}"
            git push --tags
workflows:
  version: 2
  create_detail_page:
    jobs:
      - checkout
      - render-html:
          requires:
            - checkout
      - push-to-repository:
          requires:
            - render-html
